Hanswind/EZ.ai

- ez.ai/client/src/components/ChatbotBuild/ChatbotBuildLayout.css
- ez.ai/client/src/components/ChatbotBuild/Tabs.css
> Update builder layout

- ez.ai/client/src/components/ChatbotBuild/ChatbotBuild.css
- ez.ai/client/src/components/ChatbotBuild/Tabs.css
- ez.ai/client/src/components/ChatbotBuild/ToolAdvance.js
- ez.ai/client/src/components/ChatbotBuild/ToolBasic.css
- ez.ai/client/src/components/ChatbotBuild/ToolBasic.js
- ez.ai/client/src/components/ChatbotBuild/ToolKeyword.css
- ez.ai/client/src/components/ChatbotBuild/ToolKeyword.js
- ez.ai/client/src/components/ChatbotBuild/ToolStatus.css
빌더페이지 요소 선택 창 내부 선택 요소 부분 기능 및 디자인 업데이트
> Builder tab menu selector update

- ez.ai/client/src/components/ChatbotBuild/ChatbotBuild.js
- ez.ai/client/src/components/ChatbotBuild/Main.js
- ez.ai/client/src/components/ChatbotBuild/Tabs.css
- ez.ai/client/src/components/ChatbotBuild/ToolBasic.css
- ez.ai/client/src/components/ChatbotBuild/ToolKeyword.css
- ez.ai/client/src/components/ChatbotBuild/ToolStatus.css
- ez.ai/client/src/components/ChatbotBuild/ToolStatus.js
요소 메뉴중 키워드 메뉴와 기본 매뉴 레이아웃 및 css, js 일부 수정 (미완)
> Updatetab menu

- ez.ai/client/src/components/ChatbotBuild/ToolStatus.css
- ez.ai/client/src/components/ChatbotBuild/ToolStatus.js
> Status tool Update

- ez.ai/client/src/components/ChatbotBuild/ChatbotBuildLayout.css
- ez.ai/client/src/components/ChatbotBuild/Main.css
- ez.ai/client/src/components/ChatbotBuild/Main.js
Change Main.js / Main.css / ChatbotBuildLayout.css 
(1) Main.js : main-header / main-contents / main-footer , three parts
(2) Main.css : Modify CSS code to look like telegram messenger
(3) ChatbotLayout.css : only Modify "BuilderMain" part
> Update ChatbotBuild page (Telegram Interface, incompleted)

- ez.ai/client/src/components/ChatbotBuild/Main.css
- ez.ai/client/src/components/ChatbotBuild/Main.js
- ez.ai/client/src/components/ChatbotList/BotItem/BotItem.css
- ez.ai/client/src/components/ChatbotList/ChatbotList.css
- ez.ai/client/src/components/ChatbotList/InputBot/InputBot.css
(1) Main.js , Main. css : add GoogleMap API , preview image and any other UI
(2) ChatbotList.css, BotItem.css, InputBot.css : add 'transition' effect
> Update BuilderMain Interface

- ez.ai/client/src/components/ChatbotBuild/Main.css
- ez.ai/client/src/components/ChatbotBuild/Main.js
(1) scrollbar 모양을 조금 다듬었음
(2) main-contents의 height가 overflow된 후, content 추가될때마다 스크롤 최하단으로 이동.
> Update BuilderMain Scrollbar

- ez.ai/client/src/components/ChatbotBuild/Main.js
- ez.ai/client/src/components/ChatbotBuild/ToolBasic.js
- ez.ai/client/src/components/ChatbotBuild/ToolKeyword.js
- ez.ai/client/src/components/ChatbotBuild/ToolStatus.js
status창과 main창 input 연동 (text)
> Sync between status and main

- ez.ai/client/src/components/ChatbotBuild/ChatbotBuild.js
- ez.ai/client/src/components/ChatbotBuild/Main.js
- ez.ai/client/src/components/ChatbotBuild/ToolStatus.js
> sync rest input

- ez.ai/client/src/components/ChatbotBuild/Main.css
- ez.ai/client/src/components/ChatbotBuild/Main.js
- ez.ai/client/src/components/ChatbotBuild/ToolStatus.js
(1) Main.js, Main.css: 각 main-content 마다 옆에 삭제 버튼 띄움. (나중에 누르면 메세지 버블 제거되는 용)
(2) ToolStatus. js : 페이지 오류 뜨길래 </div> 태그 하나 삭제함.
> Update content 'delete' button (동작 x)

- ez.ai/client/src/components/ChatbotBuild/Main.css
- ez.ai/client/src/components/ChatbotBuild/Main.js
Main 상의 image url 입력창에 변화가 생기면 그 이미지를 바로 띄우는 것으로 함.
> Update BuilderMain imagePreview

- ez.ai/client/src/components/ChatbotBuild/ChatbotBuild.js
- ez.ai/client/src/components/ChatbotBuild/ChatbotBuildLayout.css
- ez.ai/client/src/components/ChatbotBuild/Main.css
- ez.ai/client/src/components/ChatbotBuild/Main.js
- ez.ai/client/src/components/ChatbotBuild/ToolAdvance.js
- ez.ai/client/src/components/ChatbotBuild/ToolBasic.js
- ez.ai/client/src/components/ChatbotBuild/ToolKeyword.js
input 입력 자체에서 width값 조정이 어려워서 input 창을 없애고 div  로만 진행
스크롤 버그 조정
> Update Main.js Scroll bug , Delete text input

- ez.ai/client/src/components/ChatbotBuild/Main.js
- ez.ai/package-lock.json
- ez.ai/package.json
> Post data separately

- ez.ai/client/src/components/ChatbotBuild/ChatbotBuild.js
- ez.ai/client/src/components/ChatbotBuild/Main.css
- ez.ai/client/src/components/ChatbotBuild/Main.js
- ez.ai/client/src/components/ChatbotBuild/ToolAdvance.js
(1) Main.js, ChatbotBuild.js, ToolAdvance.js :   리스트 생성 할 때 하단 바 올라오게 함.
(2) Main.js : 문서, 비디오, 오디오 말풍선 구현 테스트
> Add code in Main.js to make the "bottom" visible when adding a list

- ez.ai/client/src/components/ChatbotBuild/ChatbotBuild.js
- ez.ai/client/src/components/ChatbotBuild/Main.js
- ez.ai/client/src/components/ChatbotBuild/ToolKeyword.js
- ez.ai/client/src/components/ChatbotBuild/ToolStatus.js
> Check extension

- ez.ai/client/src/components/ChatbotBuild/ChatbotBuild.js
- ez.ai/client/src/components/ChatbotBuild/Main.js
- ez.ai/client/src/components/ChatbotBuild/ToolKeyword.js
- ez.ai/client/src/components/ChatbotBuild/ToolStatus.js
> Revert "Check extension"

- ez.ai/client/src/components/ChatbotBuild/Main.js
- ez.ai/client/src/components/ChatbotBuild/ToolStatus.js
Main.js : 충돌나지 않게 코드 합병
ToolStatus.js : fileRef => imageRef로 교체해서 undefined error 수정
> fix undefined error and merge code

- ez.ai/client/src/components/ChatbotBuild/ChatbotBuild.js
- ez.ai/client/src/components/ChatbotBuild/Main.js
- ez.ai/client/src/components/ChatbotBuild/ToolKeyword.js
- ez.ai/client/src/components/ChatbotBuild/ToolStatus.js
1.삭제버튼완료
-하나의 div안에 클릭이벤트가 2개여서 중복으로 일어나는게 원인=>입력창과 삭제버튼 나눔
2.처음시작 시 welcom키워드 적용
> Remove button

- ez.ai/client/src/components/ChatbotBuild/Status/BasicStatus/AudioStatus.js
- ez.ai/client/src/components/ChatbotBuild/Status/BasicStatus/FileStatus.js
- ez.ai/client/src/components/ChatbotBuild/Status/BasicStatus/VideoStatus.js
- ez.ai/client/src/components/ChatbotBuild/ToolStatus.js
> Choikeonwoo

- ez.ai/client/src/components/ChatbotBuild/Main.js
- ez.ai/client/src/components/ChatbotBuild/Status/AdvanceStatus/KeyboardStatus.js
- ez.ai/client/src/components/ChatbotBuild/Status/AdvanceStatus/KeywordPopUp.js
- ez.ai/client/src/components/ChatbotBuild/ToolAdvance.js
> Change list content

- ez.ai/client/src/components/ChatbotBuild/Main.js
- ez.ai/client/src/components/ChatbotBuild/VirtualKeyboard.js
> seperate file 'VirtualKeyboard'  from Main.js

- ez.ai/client/src/components/ChatbotBuild/Main.css
- ez.ai/client/src/components/ChatbotBuild/VirtualKeyboard.js
CSS Rename ; main-keyboard -> virtual-keyboard
> fix css error and Rename

- ez.ai/client/src/components/ChatbotBuild/ChatbotBuild.js
- ez.ai/client/src/components/ChatbotBuild/Main.js
- ez.ai/client/src/components/ChatbotBuild/ToolAdvance.js
- ez.ai/client/src/components/ChatbotBuild/ToolBasic.js
- 한 키워드에 버튼형 리스트 0개 아니면 1개이며, 버튼형 리스트 생성한 후에는 다른 버튼들이 눌리지 않도록 alert 띄움.
- (사소한 것) 작업 중 쉽게 비교, 분석하기 위해 컴포넌트 props들 알파벳 순으로 정리한 것 뿐. 별 의미 없음.
- (ToolBasic.js , ToolAdvance.js : onClick 내용이 복잡해져서 handleClick 함수로 간결하게 정리)
> Add func 'alertForKeywordCompleted' and state 'keywordCompleted'

- ez.ai/client/src/components/ChatbotBuild/ToolAdvance.js
[고급] > [스티커] 누를 때도 키워드 객체의 completed 값이 true되는 부분 수정.
ToolAdvance.js : 조건부 연산자 ? : 사용 시, 이중 작업 코드를 쓰면 에러가 떠서 모두 if-else로 대체)
> fix error (Alert error)

- ez.ai/client/src/components/Header.js
- ez.ai/client/src/reducer/user.js
- ez.ai/client/src/saga/user.js
- ez.ai/config/config.json
- ez.ai/routes/auth.js
> 로그인 유지,로그아웃

- ez.ai/client/src/components/ChatbotBuild/Sidebar/Sidebar.css
- ez.ai/client/src/components/ChatbotBuild/Sidebar/Sidebar.js
- ez.ai/client/src/components/ChatbotBuild/Sidebar/SidebarPreview.js
> Fix Chatbotbuilder Sidebar

- ez.ai/client/src/components/ChatbotBuild/Status/BasicStatus/AudioStatus.js
- ez.ai/client/src/components/ChatbotBuild/Status/BasicStatus/FileStatus.js
- ez.ai/client/src/components/ChatbotBuild/Status/BasicStatus/VideoStatus.js
- ez.ai/client/src/components/ChatbotList/BotItem/BotItem.css
- ez.ai/client/src/components/ChatbotList/BotItem/BotItem.js
- ez.ai/client/src/components/ChatbotList/ChatbotList.js
- ez.ai/client/src/components/ChatbotList/Popup/Popup.css
- ez.ai/client/src/components/ChatbotList/Popup/Popup.js
- ez.ai/client/src/components/ChatbotList/Popup/TokenChkPopup.js
- ez.ai/client/src/components/ChatbotList/Popup/TokenPopup.js
- ez.ai/models/chatbotData.js
- ez.ai/routes/chatbotData.js
> Update ChatbotList page

- ez.ai/client/src/components/ChatbotBuild/Preview/Preview.css
- ez.ai/client/src/components/ChatbotBuild/Sidebar/Sidebar.css
- ez.ai/client/src/components/ChatbotBuild/Sidebar/Sidebar.js
- ez.ai/client/src/components/ChatbotBuild/Sidebar/SidebarPreview.js
- ez.ai/client/src/components/ChatbotBuild/Tabs/Tabs.css
- ez.ai/client/src/components/ChatbotBuild/Tabs/Tabs.js
-사이드바 메뉴의 CSS의 색상(color)을 화이트 + 그레이 테두리로 바꿨습니다.
-아이콘(fontawesome)을 임시로 넣었습니다.
툴팁과 슬라이드 CSS를 넣을까 고민중입니다. 
거의 네이버 웨일과 흡사한 방향이라 생각하심 됩니다.
> Fix Sidebar CSS

- ez.ai/client/src/components/ChatbotBuild/Sidebar/Sidebar.css
- ez.ai/client/src/components/ChatbotBuild/Sidebar/Sidebar.js
- ez.ai/client/src/components/ChatbotBuild/Sidebar/SidebarTab.js
- To clarify the meaning,  i have modified the 'file name' and 'state 'activeSideOverlay''s value'( 의미를 명확히 하기 위해 이름 수정)
- Update Sidebar animation spped '0.6s' to '0.3s' (사이드바 열고 닫히는 속도 0.3s로 수정)
> Rename 'SidebarPreview.js' to 'SidebarTab.js' and Update

- ez.ai/client/src/components/ChatbotBuild/Sidebar/SidebarComponents/SidePreview.css
- ez.ai/client/src/components/ChatbotBuild/Sidebar/SidebarComponents/SidePreview.js
- ez.ai/client/src/components/ChatbotBuild/Sidebar/SidebarComponents/SideVersion.js
- ez.ai/client/src/components/ChatbotBuild/Status/AdvanceStatus/KeyboardStatus.js
> Update side preview

- ez.ai/client/src/components/ChatbotBuild/Preview/AdvancePreview/ListPreview.js
- ez.ai/client/src/components/ChatbotBuild/Preview/BasicPreview/AudioPreview.js
- ez.ai/client/src/components/ChatbotBuild/Preview/BasicPreview/FilePreview.js
- ez.ai/client/src/components/ChatbotBuild/Preview/BasicPreview/ImagePreview.js
- ez.ai/client/src/components/ChatbotBuild/Preview/BasicPreview/LocationPreview.js
- ez.ai/client/src/components/ChatbotBuild/Preview/BasicPreview/TextPreview.js
- ez.ai/client/src/components/ChatbotBuild/Preview/BasicPreview/VideoPreview.js
- ez.ai/client/src/components/ChatbotBuild/Preview/Preview.css
- ez.ai/client/src/components/ChatbotBuild/Preview/Preview.js
- now 변수를 이용, 현재 클릭한 요소에 대한 강조를 보여줌
- 'Preview' folder 에 있는 파일들만 수정
> Update CSS for Focusing Element  using 'now' variable

- ez.ai/client/src/components/ChatbotBuild/Sidebar/SidebarComponents/SidePreview.js
> Side preview image

- ez.ai/client/src/components/ChatbotBuild/Sidebar/SidebarComponents/SideVersion.js
- ez.ai/client/src/reducer/chatbot.js
> Fix side version bug

- ez.ai/client/src/components/ChatbotBuild/BuilderInfo.js
> Set prompt

- ez.ai/client/src/components/ChatbotBuild/Preview/AdvancePreview/ListPreview.js
- ez.ai/client/src/components/ChatbotBuild/Preview/BasicPreview/AudioPreview.js
- ez.ai/client/src/components/ChatbotBuild/Preview/BasicPreview/FilePreview.js
- ez.ai/client/src/components/ChatbotBuild/Preview/BasicPreview/ImagePreview.js
- ez.ai/client/src/components/ChatbotBuild/Preview/BasicPreview/LocationPreview.js
- ez.ai/client/src/components/ChatbotBuild/Preview/BasicPreview/TextPreview.js
- ez.ai/client/src/components/ChatbotBuild/Preview/BasicPreview/VideoPreview.js
- ez.ai/client/src/components/ChatbotBuild/Preview/Preview.css
- ez.ai/client/src/components/Header.js
- 챗봇 만들기 버튼 삭제하고, 로그인 된 상태에서만 챗봇 목록 버튼 보이게 함.
- 로그아웃 할 때 사라지는 속도가 조금 느리나, 기능은 정상
> Delete '챗봇만들기' , Make '챗봇목록' button visible when logged in

- ez.ai/client/src/components/ChatbotBuild/BuilderInfo.js
> Fix save flag

- ez.ai/client/src/components/ChatbotBuild/BuilderInfo.js
> Fix prompt

- ez.ai/client/src/components/ChatbotBuild/Preview/BasicPreview/LocationPreview.js
- ez.ai/client/src/components/ChatbotBuild/Preview/Preview.js
- ez.ai/client/src/components/ChatbotBuild/Status/BasicStatus/LocationStatus.js
- ez.ai/client/src/components/ChatbotBuild/api/GoogleMapPresenter.js
> Apply google map

- ez.ai/client/src/components/ChatbotList/Popup/AddPlatformPopup.js
- ez.ai/client/src/components/ChatbotList/Popup/Popup.css
팝업 창에 '토큰 발급 받는 법'으로 가이드 페이지 향하게 링크했습니다.
> Add Link to guide page in AddPlatformPopup

- ez.ai/client/src/components/ChatbotBuild/BuilderInfo.js
- ez.ai/client/src/components/ChatbotBuild/Sidebar/SidebarComponents/SideVersion.css
- ez.ai/client/src/components/ChatbotBuild/Sidebar/SidebarComponents/SideVersion.js
- ez.ai/client/src/components/ChatbotList/ChatbotList.js
- ez.ai/client/src/reducer/chatbot.js
- ez.ai/client/src/saga/chatbot.js
- ez.ai/models/chatbotData.js
- ez.ai/routes/chatbotData.js
> Deploy Chatbot

- ez.ai/client/src/components/ChatbotBuild/ChatbotBuild.js
- ez.ai/client/src/components/ChatbotList/ChatbotList.js
- ez.ai/client/src/components/Header.js
> confirm login

- ez.ai/client/package-lock.json
- ez.ai/client/package.json
- ez.ai/client/src/components/ChatbotBuild/BuilderInfo.js
- ez.ai/client/src/components/ChatbotBuild/ChatbotBuild.js
- ez.ai/client/src/components/ChatbotBuild/Preview/Preview.css
- ez.ai/client/src/components/ChatbotBuild/Preview/Preview.js
- ez.ai/client/src/components/ChatbotBuild/Sidebar/Sidebar.css
- ez.ai/client/src/components/ChatbotBuild/Sidebar/Sidebar.js
- ez.ai/client/src/components/ChatbotBuild/Sidebar/SidebarComponents/SidePreview.css
- ez.ai/client/src/components/ChatbotBuild/Sidebar/SidebarComponents/SidePreview.js
- ez.ai/client/src/components/ChatbotBuild/Status/ToolStatus.css
- ez.ai/client/src/components/ChatbotBuild/Status/ToolStatus.js
- ez.ai/client/src/components/ChatbotList/BotItem/BotItem.css
- ez.ai/client/src/components/ChatbotList/BotItem/BotItem.js
- ez.ai/client/src/components/ChatbotList/ChatbotList.js
- ez.ai/client/src/components/ChatbotList/Popup/Popup.js
- 작업 도중 챗봇이 생성되지 않아 확인 작업이 안됐습니다.  지우지 않아도 되는 부분도 있었지만 일단 kakaotalk 관련 작성된 코드는 거의 제거했습니다.
- BotItem 관련 중 카카오톡이 있던 영역 박스는 삭제되지 않았을 거라 추정하지만 확인할 수 없었습니다.
> Remove Code about 'Kakao'

- ez.ai/client/src/components/ChatbotBuild/Sidebar/SidebarComponents/SidePreview.css
- ez.ai/client/src/components/ChatbotBuild/Sidebar/SidebarComponents/SidePreview.js
-  텔레그램 sidebar 고정메뉴바 콘텐츠 연동 시도 .
-  listContent.elem 으로 시도헀으니 빈 배열만 나와서 listContent.keywordLink 활용
-  자판 css를 'grid'를 활용해서 배치
> Update Sidebar. previewKeyboard are connected with 'listContent.keywordLink'

- ez.ai/client/src/components/ChatbotBuild/Sidebar/SidebarComponents/SidePreview.css
- ez.ai/client/src/components/ChatbotBuild/Sidebar/SidebarComponents/SidePreview.js
- sidebar의 고정 메뉴 텔레그램과 유사하게 인터페이스 설정
> Update sidebar keyboard interface

- ez.ai/client/src/components/Home.js
- 노트북에서 작업하기위해 새로 깃 브랜치를 파봤습니다.
- 자잘한 오류가 많아서 일단 커밋이 되는지 확인해보고자 커밋했습니다.
> Update paragraph in Home.js (Test commit)

- ez.ai/client/src/components/ChatbotBuild/Preview/Preview.js
-   ClickedBuilderMain 함수 삭제
- 메인(Preview)의 배경 클릭 시 하단의 가상 키보드(virtualKeyboard) 숨기는 기능 삭제
> Delete function 'ClickedBuilderMain' in Preview

- ez.ai/client/package-lock.json
- ez.ai/client/package.json
- ez.ai/client/public/index.html
- ez.ai/client/src/components/ChatbotBuild/Preview/DefaultPreview/BasicPreview/LocationPreview.js
- ez.ai/client/src/components/ChatbotBuild/Preview/FacebookPreview/BasicPreview/LocationPreview.js
- ez.ai/client/src/components/ChatbotBuild/Preview/LinePreview/BasicPreview/LocationPreview.js
- ez.ai/client/src/components/ChatbotBuild/Preview/TelegramPreview/BasicPreview/LocationPreview.js
- ez.ai/client/src/components/ChatbotBuild/Status/BasicStatus/LocationStatus.js
- ez.ai/client/src/components/ChatbotBuild/api/GoogleMapPresenter.css
- ez.ai/client/src/components/ChatbotBuild/api/GoogleMapPresenter.js
- ez.ai/client/src/components/ChatbotBuild/api/Map.js
- ez.ai/client/src/components/ChatbotBuild/api/PlacesAutocomplete .js
- ez.ai/client/src/components/ChatbotBuild/api/PlacesAutocomplete2.js
- ez.ai/client/src/components/ChatbotList/ChatbotList.js
- ez.ai/client/src/components/FAQ.js
- ez.ai/client/src/reducer/user.js
- ez.ai/client/yarn.lock
client폴더에서 npm install 필수
페이지 접근제한
(/profiel, /chatbotlist, /chatbotbuild)
구글맵(실제 존재하는 주소만 설정할 수 있게 검색으로만 설정 가능)
> Access Control,GoogleMap (Refactoring...)

- ez.ai/client/src/components/ChatbotBuild/Preview/Preview.js
- ez.ai/client/src/components/ChatbotBuild/Preview/TelegramPreview/AdvancePreview/ListPreview.js
- ez.ai/client/src/components/ChatbotBuild/Status/AdvanceStatus/PersistentStatus.js
- 리스트의 Question, Ask a Question 을 삭제합니다.
> Delete Question, Ask a Question in List

- ez.ai/client/src/components/ChatbotBuild/BuilderInfo.js
- ez.ai/client/src/components/ChatbotBuild/Sidebar/SidebarComponents/SideVersion.js
- ez.ai/client/src/components/ChatbotBuild/Status/BasicStatus/AudioStatus.js
- ez.ai/client/src/components/ChatbotBuild/Status/BasicStatus/FileStatus.js
- ez.ai/client/src/components/ChatbotBuild/Status/BasicStatus/VideoStatus.js
- ez.ai/client/src/reducer/chatbot.js
- ez.ai/routes/audio.js
- ez.ai/routes/chatbotData.js
- ez.ai/routes/file.js
- ez.ai/routes/video.js
> Create another deploy button

- ez.ai/client/src/components/ChatbotBuild/Tabs/ToolAdvance.js
- ez.ai/client/src/components/ChatbotBuild/Tabs/ToolBasic.js
- ez.ai/package.json
ISSUE : 고정 메뉴로 이름 바꿨는데 경고창에는 [버튼형 리스트]로 나옴
=> [고정 메뉴]라고 표시되도록 수정
& 
update package.json
> Fix issue where alert message shows '버튼형 리스트', not '고정 메뉴'

- ez.ai/client/src/components/ChatbotBuild/Status/AdvanceStatus/Templates/ButtonTemplateStatus.css
- ez.ai/client/src/components/ChatbotBuild/Status/AdvanceStatus/Templates/ButtonTemplateStatus.js
> 버튼템플릿 ui 구현

- ez.ai/client/src/components/ChatbotBuild/Status/BasicStatus/AudioStatus.js
- ez.ai/client/src/components/ChatbotBuild/Status/ToolStatus.js
> Include duration size on DB

- ez.ai/.gitignore
- ez.ai/client/src/components/ChatbotBuild/Status/AdvanceStatus/Templates/ButtonTemplateStatus.js
- ez.ai/client/src/components/ChatbotBuild/Tabs/ToolAdvance.js
> Image upload,  save into JSON funciton

- ez.ai/client/src/components/ChatbotBuild/Sidebar/SidebarComponents/SideVersion.css
> 이슈 #112 merge 요청

- ez.ai/client/src/components/ChatbotBuild/Status/AdvanceStatus/Templates/ButtonTemplateStatus.js
- ez.ai/client/src/components/ChatbotBuild/Status/AdvanceStatus/Templates/CarouselTemplateStatus.css
- ez.ai/client/src/components/ChatbotBuild/Status/AdvanceStatus/Templates/CarouselTemplateStatus.js
> #121 슬라이드 요소 기본 인터페이스 구축, 슬라이드 actions 추가 버튼 구현

- ez.ai/client/src/components/ChatbotBuild/Tabs/ToolAdvance.js
- ez.ai/client/src/components/ChatbotBuild/Tabs/ToolBasic.js
한 키워드 당 하나의 'Button Template'을 위해 코드 개선
> #119 Update code for One ButtonTemplate per Keyword

- ez.ai/client/src/components/ChatbotBuild/Status/AdvanceStatus/Templates/ButtonTemplateStatus.js
- ez.ai/client/src/components/ChatbotBuild/Tabs/ToolAdvance.js
> Add Text data in action

- ez.ai/routes/audio.js
- ez.ai/routes/webhook.js
- 오디오 관련 이슈 해결했습니다.
- 현재 m4a, mp3 모두 동작하게 해놨습니다. 
- 더 많은 파일들을 테스트 해볼 필요성은 있습니다.
> #156 오디오 코드 수정

- ez.ai/client/src/components/ChatbotBuild/Status/AdvanceStatus/Templates/ButtonTemplateStatus.css
- ez.ai/client/src/components/ChatbotBuild/Status/StatusPopups/HelpPopup.css
- ez.ai/client/src/components/ChatbotBuild/Status/StatusPopups/HelpPopup.js
- ez.ai/client/src/components/ChatbotBuild/Status/ToolStatus.css
- ez.ai/client/src/components/ChatbotBuild/Status/ToolStatus.js
- HelpPopup 으로 도움말 부분 따로 관리
- 툴팁으로 인한 레이아웃 겹침 현상 개선
> #158 Update code for help tooltip

- ez.ai/client/src/components/ChatbotBuild/Status/ToolStatus.css
- ez.ai/client/src/components/ChatbotBuild/api/GoogleMapPresenter.css
- ez.ai/client/src/components/ChatbotBuild/api/GoogleMapPresenter.js
- ez.ai/client/src/components/ChatbotBuild/api/PlacesAutocomplete2.js
> #153 위치 요소 검색창 인터페이스 개선

- ez.ai/client/src/components/ChatbotList/Popup/AddPlatformPopup.js
- ez.ai/client/src/components/ChatbotList/Popup/Popup.css
챗봇 목록에서 플랫폼 토큰 작성 팝업 하단의 '토큰 생성하는 법' 을 삭제. 가이드라인으로 이동하기 때문
> #159 Remove Guide link in AddPlatformPopup

- ez.ai/client/src/components/ChatbotBuild/Status/StatusPopups/HelpPopup.css
- ez.ai/client/src/components/ChatbotBuild/Status/StatusPopups/HelpPopup.js
- ez.ai/client/src/components/ChatbotBuild/Status/ToolStatus.css
- 도움말 클릭 시 도움말 텍스트가 팝업 하듯 뜨고 다시 클릭하면 사라지도록
> Update 'help' for using click Event, not hover effect

- ez.ai/client/src/components/ChatbotList/BotItem/BotItem.css
- ez.ai/client/src/components/ChatbotList/BotItem/BotItem.js
- ez.ai/client/src/components/ChatbotList/BotList/BotList.js
- ez.ai/client/src/components/ChatbotList/ChatbotList.css
- ez.ai/client/src/components/ChatbotList/ChatbotList.js
- ez.ai/client/src/components/ChatbotList/InputBot/InputBot.css
- ez.ai/client/src/components/ChatbotList/Popup/AddPlatformPopup.js
연동 토큰 정보 불러오는대신 텍스트로 연동 정보 보여줌
> #199 챗봇 목록 인터페이스

- ez.ai/client/src/components/ChatbotBuild/ChatbotBuild.css
- ez.ai/client/src/components/ChatbotBuild/ChatbotBuild.js
- ez.ai/client/src/components/ChatbotBuild/Sidebar/Sidebar.js
- ez.ai/client/src/components/ChatbotBuild/Sidebar/SidebarComponents/SideSetting.css
- ez.ai/client/src/components/ChatbotBuild/Sidebar/SidebarComponents/SideSetting.js
- ez.ai/client/src/components/ChatbotList/BotItem/BotItem.js
- ez.ai/client/src/components/ChatbotList/BotItem/PlatformConnect.js
- ez.ai/client/src/components/ChatbotList/Popup/Popup.css
- Seperate Platform connecting part from BotItem.js
- BotItem.js에서 플랫폼 연동하는 부분을 따로 파일 분리해서 재사용에 용이하도록 함.
> #205 사이드바 설정 페이지 디자인

- ez.ai/client/src/components/ChatbotBuild/Preview/LinePreview/LinePreview.js
- ez.ai/client/src/components/ChatbotBuild/Preview/Preview.js
- ez.ai/client/src/components/ChatbotBuild/Preview/TelegramPreview/TelegramPreview.js
- 테마 텍스트 가운데 정렬 및 키워드 형식 변경 ('KEYWORD:' 부분 삭제)
> Update: align theme  text and  update keyword form in Main

- ez.ai/client/src/components/ChatbotBuild/Preview/LinePreview/LinePreview.js
- ez.ai/client/src/components/ChatbotBuild/Preview/TelegramPreview/TelegramPreview.js
- 라인은 'Welcome' -> '대화방에 입장하셨습니다' 로 수정
- 텔레그램은 'Welcome' -> '/start'로 수정
> Update Keyword 'Welcome' text in Main

- ez.ai/client/src/components/ChatbotBuild/Preview/LinePreview/LinePreview.js
- ez.ai/client/src/components/ChatbotBuild/Preview/TelegramPreview/TelegramPreview.js
- ez.ai/client/src/components/ChatbotBuild/Sidebar/Sidebar.css
> #213 fix bug in sidebar tooltip

- ez.ai/client/src/components/ChatbotBuild/Preview/TelegramPreview/TelegramPreview.css
- ez.ai/client/src/components/ChatbotBuild/Sidebar/SidebarComponents/SidePreview.css
- ez.ai/client/src/components/ChatbotBuild/Sidebar/SidebarComponents/SidePreview.js
- 텔레그램 용 사이드 바 미리보기에서 버튼 템플릿을 띄울 때 이미지, 타이틀, 텍스트, 고정메뉴로 각 요소가 따로따로 분리되어 보이게끔 함.
> Update ButtonsTemplate interface in Sidebar Preview for Telegram

- ez.ai/client/src/components/ChatbotBuild/Sidebar/Sidebar.js
- ez.ai/client/src/components/ChatbotBuild/Sidebar/SidebarComponents/SidePreview.js
- ez.ai/client/src/components/ChatbotBuild/Sidebar/SidebarComponents/SideVersion.js
- to limit the number of 'Line' keywords.
- 해당 고정메뉴의 키워드 개수가 5개 이상이면 라인 인터페이스에 고정메뉴가 보이지 않음.
> Updates the permanent menu in the sidebar preview 
